languages =[
    {
        "key"       :   "en",
        "lang"      :   "English",
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/english",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    }, 
    {
        "key"       :   "ar",
        "lang"      :   "Arabic",
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/arabic",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    }, 
    {
        "key"       :   "ja",
        "lang"      :   "Japanese",
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/japanese",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    },
    {
        "key"       :   "ko",
        "lang"      :   "Korean",
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/korean",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    },
    {
        "key"       :   "es",
        "lang"      :   "Spanish", 
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/spanish",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    },
    {
        "key"       :   "th",
        "lang"      :   "Thai",
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/thai",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    },
    {
        "key"       :   "pt",
        "lang"      :   "Portuguese",
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/portuguese",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    },
    {
        "key"       :   "fr",
        "lang"      :   "French", 
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/french",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    },
    {
        "key"       :   "in",
        "lang"      :   "Indonesian", 
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/indonesian",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    },  
    {
        "key"       :   "tl",
        "lang"      :   "Tagalog",
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/tagalog",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    }, 
    {
        "key"       :   "pl",
        "lang"      :   "Polish",
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/polish",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    }, 
    {
        "key"       :   "tr",
        "lang"      :   "Turkish",
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/turkish",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    }, 
    {
        "key"       :   "ru",
        "lang"      :   "Russian",
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/russian",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    }, 
    {
        "key"       :   "ca",
        "lang"      :   "Catalan",
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/catalan",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    },
    {
        "key"       :   "und",
        "lang"      :   "UnDefined",
        "tumblr"    :   "https://elwizaracom.tumblr.com",
        "pinterest" :   "https://www.pinterest.com/elwizaracom/undefined",
        "reddit"    :   "https://www.reddit.com/user/elwizaracom",
    }, 
]